<?php

class NotebookProduct extends Product implements IGadget
{
  public $cpu;
  public function __construct($name, $price,$cpu)
  {
            parent::__construct($name,$price);
            $this->cpu=$cpu;

  }
    public function getCase()
    {
        // TODO: Implement getCase() method.
    }

    public function getPrice()
    {
        return parent::getPrice(); // TODO: Change the autogenerated stub
    }

    public function getProduct()
    {
        $out = parent::getProduct();
        $out .="Процессор : {$this->cpu}<br>";
        return $out;
    }
    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getCpu()
    {
        return $this->cpu;
    }
    public function addProduct($name, $price,$NumPages=0)
    {
        // TODO: Implement addProuct() method.
        var_dump($name);
        var_dump($price);
        var_dump($NumPages);
    }

}

?>